openapi: 3.0.0
info:
  title: "Admin API - Sao kê & Đối soát"
  description: |
    API dành cho quản trị viên, bao gồm các chức năng:
    1.  Xác thực (Đăng ký, Đăng nhập).
    2.  Tải lên và xử lý file sao kê Excel từ các ngân hàng.
    3.  Thực hiện đối soát giao dịch tự động.
  version: "1.0.0"
servers:
  - url: "/api"
    description: "Admin API Server"
tags:
  - name: "Authentication"
    description: "API xác thực quản trị viên"
  - name: "Statement Processing"
    description: "API để xử lý file sao kê ngân hàng"
  - name: "Reconciliation"
    description: "API để đối soát giao dịch"
paths:
  /auth/register:
    post:
      tags:
        - "Authentication"
      summary: "Đăng ký tài khoản admin mới"
      description: "Tạo một tài khoản quản trị viên mới. Endpoint này nên được bảo vệ hoặc vô hiệu hóa sau khi đã có tài khoản admin."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthInput'
      responses:
        '201':
          description: "Đăng ký thành công."
        '400':
          description: "Tên đăng nhập đã tồn tại hoặc dữ liệu không hợp lệ."
  /auth/login:
    post:
      tags:
        - "Authentication"
      summary: "Đăng nhập tài khoản admin"
      description: "Xác thực người dùng và trả về một JSON Web Token (JWT)."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthInput'
      responses:
        '200':
          description: "Đăng nhập thành công, trả về token."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginSuccessResponse'
        '401':
          description: "Sai tên đăng nhập hoặc mật khẩu."
  /xlsx/mbbank:
    post:
      tags:
        - "Statement Processing"
      summary: "Tải lên và xử lý sao kê MBBank"
      security:
        - bearerAuth: []
      description: "**Yêu cầu xác thực.** Endpoint nhận file sao kê Excel (.xlsx) từ MBBank, phân tích và lưu các giao dịch."
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                statement:
                  type: string
                  format: binary
                  description: "File sao kê Excel (.xlsx) của MBBank."
      responses:
        '201':
          description: "Xử lý sao kê thành công."
        '400':
          description: "Không có file hoặc định dạng file không hợp lệ."
        '401':
          description: "Chưa xác thực."
  /xlsx/bidv:
    post:
      tags:
        - "Statement Processing"
      summary: "Tải lên và xử lý sao kê BIDV"
      security:
        - bearerAuth: []
      description: "**Yêu cầu xác thực.** Endpoint nhận file sao kê Excel (.xlsx) từ BIDV, phân tích và lưu các giao dịch."
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                statement:
                  type: string
                  format: binary
                  description: "File sao kê Excel (.xlsx) của BIDV."
      responses:
        '201':
          description: "Xử lý sao kê thành công."
        '400':
          description: "Không có file hoặc định dạng file không hợp lệ."
        '401':
          description: "Chưa xác thực."
  /reconciliation/check:
    post:
      tags:
        - "Reconciliation"
      summary: "Đối soát các giao dịch đang chờ"
      security:
        - bearerAuth: []
      description: "**Yêu cầu xác thực.** Kích hoạt quá trình đối soát tự động. Hệ thống sẽ quét các giao dịch 'pending' và so khớp chúng với các bản ghi trong sao kê ngân hàng. Sẽ so khớp các trường `amount` và kiểm tra `transacCode` có nằm trong `statemententries.content`"
      responses:
        '200':
          description: "Đối soát hoàn tất."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReconciliationResponse'
        '401':
          description: "Chưa xác thực."
        '500':
          description: "Lỗi máy chủ nội bộ."
components:
  schemas:
    AuthInput:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          example: "admin"
        password:
          type: string
          example: "your_strong_password"
    LoginSuccessResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
          example: "Đăng nhập thành công."
        data:
          type: object
          properties:
            _id:
              type: string
            username:
              type: string
            token:
              type: string
    ReconciliationResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
          example: "Đối soát hoàn tất."
        data:
          type: object
          properties:
            totalChecked:
              type: integer
            successCount:
              type: integer
            failedCount:
              type: integer
            stillPendingCount:
              type: integer
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
