openapi: 3.0.0
info:
  title: "API Chứng Nhận Số"
  description: |
    API này bao gồm các chức năng:
    1.  Tạo mã QR thanh toán từ thông tin người dùng.
    2.  Tìm kiếm các giao dịch đã tạo.
    3.  Nhận, xem và quản lý phản hồi từ người dùng.
    4.  Lấy nội dung cho trang chủ (landing page).
  version: "1.0.2"

servers:
  - url: "/api"
    description: "Product API Server"

tags:
  - name: "QR Generation"
    description: "Các API liên quan đến việc tạo mã QR"
  - name: "Transaction Search"
    description: "Các API liên quan đến việc tìm kiếm giao dịch"
  - name: "Feedback"
    description: "API để nhận và quản lý phản hồi từ người dùng"
  - name: "Landing Page"
    description: "API để lấy nội dung cho trang chủ"

paths:
  /page:
    get:
      tags:
        - "Landing Page"
      summary: "Lấy dữ liệu cho trang landing page"
      description: "Endpoint này trả về toàn bộ nội dung cần thiết để hiển thị trên trang chủ (landing page) từ collection 'cms.landingpage'."
      responses:
        '200':
          description: "Lấy dữ liệu thành công."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageSuccessResponse'
        '404':
          description: "Không tìm thấy dữ liệu trang."
        '500':
          description: "Lỗi máy chủ nội bộ."

  /qr:
    post:
      tags:
        - "QR Generation"
      summary: "Tạo mã QR cho một ngân hàng cụ thể"
      description: |
        Endpoint này nhận thông tin người dùng và tên ngân hàng, sau đó tạo mã QR cho tài khoản đầu tiên đang hoạt động (isActive: true) khớp với tên ngân hàng đó.
        Nếu không tìm thấy ngân hàng khớp, nó sẽ tự động chọn tài khoản hoạt động đầu tiên làm phương án dự phòng.
      requestBody:
        description: "Đối tượng chứa thông tin người dùng và tên ngân hàng."
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInput'
      responses:
        '200':
          description: "Tạo mã QR thành công."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QrSuccessResponseWrapper'
        '400':
          description: "Dữ liệu đầu vào không hợp lệ."
        '404':
          description: "Không có tài khoản nào đang hoạt động."
        '500':
          description: "Lỗi từ server hoặc từ API của VietQR."

  /search:
    get:
      tags:
        - "Transaction Search"
      summary: "Tìm kiếm giao dịch bằng SĐT, CCCD hoặc mã giao dịch"
      description: "Endpoint này cho phép tìm kiếm giao dịch. Thông tin nhạy cảm sẽ được che đi."
      parameters:
        - name: query
          in: query
          required: true
          description: "Từ khóa tìm kiếm (SĐT, CCCD, email hoặc mã giao dịch)"
          schema:
            type: string
            example: "0912345678"
      responses:
        '200':
          description: "Tìm kiếm thành công."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResponse'
        '400':
          description: "Thiếu từ khóa tìm kiếm."
        '404':
          description: "Không tìm thấy giao dịch."
        '500':
          description: "Lỗi máy chủ nội bộ."

  /feedback:
    get:
      tags:
        - "Feedback"
      summary: "Lấy danh sách tất cả phản hồi"
      description: "Endpoint này trả về một danh sách tất cả các phản hồi đã được gửi, sắp xếp theo thời gian mới nhất."
      responses:
        '200':
          description: "Lấy danh sách thành công."
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Tìm thấy 5 phản hồi."
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Feedback'
        '500':
          description: "Lỗi máy chủ nội bộ."
    post:
      tags:
        - "Feedback"
      summary: "Gửi phản hồi của người dùng"
      description: |
        Endpoint này nhận phản hồi từ người dùng, bao gồm họ tên, email, nội dung, và một tệp đính kèm tùy chọn.
        Dữ liệu được gửi dưới dạng `multipart/form-data`.
      requestBody:
        description: "Đối tượng chứa thông tin phản hồi."
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - ho_ten
                - email
                - noi_dung
              properties:
                ho_ten:
                  type: string
                  description: "Họ và tên người gửi."
                  example: "Trần Thị B"
                email:
                  type: string
                  format: email
                  description: "Địa chỉ email người gửi."
                  example: "tranthib@email.com"
                noi_dung:
                  type: string
                  description: "Nội dung chi tiết của phản hồi."
                  example: "Giao diện rất dễ sử dụng!"
                tep_dinh_kem:
                  type: string
                  format: binary
                  description: "Tệp đính kèm (tùy chọn). Chỉ chấp nhận png, jpg, pdf."
      responses:
        '201':
          description: "Gửi phản hồi thành công."
        '400':
          description: "Dữ liệu không hợp lệ hoặc thiếu trường."
        '500':
          description: "Lỗi máy chủ nội bộ."

  /feedback/{id}:
    patch:
      tags:
        - "Feedback"
      summary: "Cập nhật trạng thái của một phản hồi (Admin)"
      description: "Cho phép admin cập nhật trạng thái của một phản hồi dựa vào ID."
      parameters:
        - name: id
          in: path
          required: true
          description: "ID của feedback cần cập nhật"
          schema:
            type: string
            example: "64f8c9b2e4b4d2a1c0e9d6f5"
      requestBody:
        description: "Đối tượng chứa trạng thái mới."
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - status
              properties:
                status:
                  type: string
                  description: "Trạng thái mới. Phải là 'pending', 'done', hoặc 'rejected'."
                  enum: [pending, done, rejected]
                  example: "done"
      responses:
        '200':
          description: "Cập nhật thành công."
        '400':
          description: "Trạng thái không hợp lệ."
        '404':
          description: "Không tìm thấy feedback."
        '500':
          description: "Lỗi máy chủ nội bộ."

components:
  schemas:
    UserInput:
      type: object
      description: "Thông tin người dùng cung cấp."
      required:
        - ho_ten
        - sdt
        - cccd
        - dia_chi
        - bankName
      properties:
        ho_ten:
          type: string
          example: "Nguyễn Văn A"
        sdt:
          type: string
          example: "0912345678"
        cccd:
          type: string
          example: "012345678912"
        dia_chi:
          type: string
          example: "Số 1, Đường X, Quận Y, Hà Nội"
        bankName:
          type: string
          example: "MBBank"
        email:
          type: string
          format: email

    QrSuccessResponse:
      type: object
      properties:
        ma_giao_dich:
          type: string
          example: "a1b2c3d4e5"
        transaction_id:
          type: number
          example: 123
        qrInfo:
          type: object
          properties:
            qrCode:
              type: string
              example: "000201010212..."
            amount:
              type: number
              example: 160000
            bankName:
              type: string
              example: "MBBank"
            accountName:
              type: string
              example: "Nguyen Hoang Viet"

    QrSuccessResponseWrapper:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
          example: "Mã QR đã được tạo thành công!"
        data:
          $ref: '#/components/schemas/QrSuccessResponse'

    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        message:
          type: string
        details:
          type: object

    SearchResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
          example: "Tìm thấy 2 giao dịch."
        data:
          type: array
          items:
            type: object
            properties:
              transactionId:
                type: number
              amount:
                type: number
              toAccount:
                type: object
                properties:
                  accountID:
                    type: string
                  accountName:
                    type: string
                  bankName:
                    type: string
              transactionCode:
                type: string
              userInfo:
                type: object
                description: "Thông tin đã được che bớt"
                properties:
                  name:
                    type: string
                    example: "Nxxxxxx Vxx A"
                  phonenum:
                    type: string
                    example: "091xxxx678"
                  id:
                    type: string
                    example: "012xxxx912"
                  address:
                    type: string
                  email:
                    type: string
              createdAt:
                type: string
                format: date-time
              status:
                type: string

    Feedback:
      type: object
      properties:
        _id:
          type: string
          example: "64f8c9b2e4b4d2a1c0e9d6f5"
        ho_ten:
          type: string
          example: "Trần Thị B"
        email:
          type: string
          example: "tranthib@email.com"
        noi_dung:
          type: string
          example: "Giao diện rất dễ sử dụng!"
        status:
          type: string
          example: "pending"
        filePath:
          type: string
          example: "uploads/tep_dinh_kem-1694025650123-123456789.pdf"
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
          
    PageSuccessResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        message:
          type: string
          example: "Lấy dữ liệu landing page thành công."
        data:
          $ref: '#/components/schemas/PageData'

    PageData:
      type: object
      description: "Toàn bộ nội dung của landing page"
      properties:
        _id:
          type: string
        header:
          type: object
          properties:
            title:
              type: string
            nav_links:
              type: array
              items:
                type: string
        main_content:
          type: object
          properties:
            search_section:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                search_info:
                  type: string
                search_button:
                  type: string
                support_link:
                  type: string
            features_section:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                features:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      details:
                        type: string
            faq_section:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                questions:
                  type: array
                  items:
                    type: string
            contact_section:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                form:
                  type: object
                  properties:
                    title:
                      type: string
                    description:
                      type: string
                    fields:
                      type: array
                      items:
                        type: string
                    submit_button:
                      type: string
                    success_message:
                      type: string
        footer:
          type: object
          properties:
            title:
              type: string
            description:
              type: string
            contact_info:
              type: object
              properties:
                address:
                  type: string
                phone:
                  type: string
                email:
                  type: string
            vision:
              type: string
            copyright:
              type: string
